// frontendV3/src/routes/_authenticated/extrato/lotes/index.tsx
import { createFileRoute, useNavigate, Link } from '@tanstack/react-router'
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import { useState } from 'react'
import { z } from 'zod'
import { api } from '@/lib/api-client'
import type { Lote, LoteStatus } from '@/features/lotes/services/schemas'
import { Badge } from '@/shared/components/badge/badge'
import { ConfirmDialog } from '@/shared/components/confirm-dialog/confirm-dialog'
import { Spinner } from '@/shared/components/spinner/spinner'
import { useSession } from '@/shared/hooks/use-session'
import { toast } from 'sonner'

export const Route = createFileRoute('/_authenticated/extrato/lotes/')({
  component: LotesPage,
  validateSearch: z.object({
    status: z.string().optional(),
    page: z.coerce.number().int().min(1).default(1),
  }),
})

const STATUS_OPTIONS: { value: LoteStatus | ''; label: string }[] = [
  { value: '', label: 'Todos' },
  { value: 'aguardando', label: 'Aguardando' },
  { value: 'processando', label: 'Processando' },
  { value: 'pendente', label: 'Pendente' },
  { value: 'concluido', label: 'Concluído' },
  { value: 'erro', label: 'Erro' },
]

const STATUS_BADGE: Record<LoteStatus, { variant: 'slate' | 'emerald' | 'amber' | 'red' | 'blue' | 'violet'; label: string }> = {
  aguardando: { variant: 'slate', label: 'Aguardando' },
  processando: { variant: 'blue', label: 'Processando' },
  pendente: { variant: 'amber', label: 'Pendente' },
  concluido: { variant: 'emerald', label: 'Concluído' },
  erro: { variant: 'red', label: 'Erro' },
}

function LotesPage() {
  const { session } = useSession()
  const navigate = useNavigate({ from: '/extrato/lotes/' })
  const qc = useQueryClient()
  const [deleteId, setDeleteId] = useState<string | null>(null)
  const search = Route.useSearch()
  const currentPage = search.page ?? 1
  const statusFilter = search.status ?? ''

  const { data, isLoading } = useQuery({
    queryKey: ['lotes', session?.cnpj, statusFilter, currentPage],
    queryFn: () => {
      const params: Record<string, string | number> = { page: currentPage, page_size: 15 }
      if (session?.cnpj) params['cnpj'] = session.cnpj
      if (statusFilter) params['status'] = statusFilter
      return api.get<{ items: Lote[]; total: number; page: number; page_size: number }>('/lotes', params)
    },
    refetchInterval: (query) => {
      const hasProcessing = query.state.data?.items.some(l => l.status === 'processando')
      return hasProcessing ? 3000 : false
    },
  })

  const deleteMutation = useMutation({
    mutationFn: (id: string) => api.delete(`/lotes/${id}`),
    onSuccess: () => {
      void qc.invalidateQueries({ queryKey: ['lotes'] })
      toast.success('Lote removido.')
      setDeleteId(null)
    },
    onError: () => toast.error('Erro ao remover lote.'),
  })

  const totalPages = data ? Math.ceil(data.total / data.page_size) : 1

  function setPage(page: number) {
    void navigate({ search: (prev) => ({ ...prev, page }) })
  }

  function setStatus(status: string) {
    void navigate({ search: (prev) => ({ ...prev, status: status || undefined, page: 1 }) })
  }

  return (
    <div className="max-w-5xl">
      <div className="flex items-center justify-between mb-6">
        <div>
          <p className="text-xs font-medium text-slate-400 uppercase tracking-widest mb-1">Extrato</p>
          <h1 className="text-2xl font-bold text-slate-900">Lotes</h1>
          <p className="text-sm text-slate-500 mt-0.5">Acompanhe os lotes de processamento de extratos.</p>
        </div>
        <Link
          to="/extrato/upload"
          className="inline-flex items-center gap-2 px-4 py-2 bg-slate-900 text-white text-sm font-medium hover:bg-slate-800 transition-colors"
        >
          + Novo Upload
        </Link>
      </div>

      {/* Filters */}
      <div className="flex items-center gap-2 mb-4 flex-wrap">
        {STATUS_OPTIONS.map(opt => (
          <button
            key={opt.value}
            onClick={() => setStatus(opt.value)}
            className={`px-3 py-1.5 text-xs font-medium border transition-colors ${
              statusFilter === opt.value
                ? 'bg-slate-900 text-white border-slate-900'
                : 'bg-white text-slate-600 border-slate-300 hover:border-slate-400'
            }`}
          >
            {opt.label}
          </button>
        ))}
      </div>

      {isLoading ? (
        <div className="flex items-center gap-2 py-8 text-slate-400"><Spinner /> Carregando...</div>
      ) : (
        <>
          <div className="border border-slate-200 bg-white">
            <table className="w-full text-sm" aria-label="Lista de lotes">
              <thead className="bg-slate-50 border-b border-slate-200">
                <tr>
                  <th scope="col" className="px-4 py-3 text-left text-xs font-medium text-slate-500 uppercase tracking-wider">Protocolo</th>
                  <th scope="col" className="px-4 py-3 text-left text-xs font-medium text-slate-500 uppercase tracking-wider">CNPJ</th>
                  <th scope="col" className="px-4 py-3 text-left text-xs font-medium text-slate-500 uppercase tracking-wider">Período</th>
                  <th scope="col" className="px-4 py-3 text-left text-xs font-medium text-slate-500 uppercase tracking-wider">Layout</th>
                  <th scope="col" className="px-4 py-3 text-left text-xs font-medium text-slate-500 uppercase tracking-wider">Status</th>
                  <th scope="col" className="px-4 py-3 text-right text-xs font-medium text-slate-500 uppercase tracking-wider">Ações</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100">
                {data?.items.map(lote => {
                  const statusInfo = STATUS_BADGE[lote.status]
                  return (
                    <tr key={lote.id} className="hover:bg-slate-50/60">
                      <td className="px-4 py-3 font-mono text-xs text-slate-700 font-medium">{lote.protocolo}</td>
                      <td className="px-4 py-3 font-mono text-xs text-slate-500">{lote.cnpj_formatado}</td>
                      <td className="px-4 py-3 text-slate-700">{lote.periodo}</td>
                      <td className="px-4 py-3 text-slate-600 truncate max-w-[160px]">{lote.nome_layout}</td>
                      <td className="px-4 py-3">
                        <Badge variant={statusInfo.variant}>
                          {lote.status === 'processando' && (
                            <span className="inline-block w-1.5 h-1.5 rounded-full bg-blue-500 mr-1.5 animate-pulse" aria-hidden="true" />
                          )}
                          {statusInfo.label}
                        </Badge>
                      </td>
                      <td className="px-4 py-3 text-right flex justify-end gap-3">
                        <Link
                          to="/extrato/lotes/$id"
                          params={{ id: lote.id }}
                          className="text-xs text-slate-600 hover:text-slate-900 transition-colors"
                        >
                          Ver
                        </Link>
                        {(lote.status === 'aguardando' || lote.status === 'erro') && (
                          <button
                            onClick={() => setDeleteId(lote.id)}
                            className="text-xs text-red-600 hover:text-red-800 transition-colors"
                            aria-label={`Remover lote ${lote.protocolo}`}
                          >
                            Remover
                          </button>
                        )}
                      </td>
                    </tr>
                  )
                })}
                {!data?.items.length && (
                  <tr>
                    <td colSpan={6} className="px-4 py-10 text-center text-sm text-slate-400">
                      Nenhum lote encontrado.
                      <Link to="/extrato/upload" className="ml-1 text-slate-600 hover:text-slate-900 underline">
                        Enviar um arquivo.
                      </Link>
                    </td>
                  </tr>
                )}
              </tbody>
            </table>
          </div>

          {/* Pagination */}
          {totalPages > 1 && (
            <div className="flex items-center justify-between mt-4 text-sm">
              <p className="text-slate-500 text-xs">
                Total: <strong>{data?.total ?? 0}</strong> lotes
              </p>
              <div className="flex items-center gap-1">
                <button
                  onClick={() => setPage(currentPage - 1)}
                  disabled={currentPage <= 1}
                  className="px-3 py-1.5 border border-slate-300 text-xs hover:bg-slate-50 disabled:opacity-40 transition-colors"
                >
                  ← Anterior
                </button>
                <span className="px-3 py-1.5 text-xs text-slate-600">
                  {currentPage} / {totalPages}
                </span>
                <button
                  onClick={() => setPage(currentPage + 1)}
                  disabled={currentPage >= totalPages}
                  className="px-3 py-1.5 border border-slate-300 text-xs hover:bg-slate-50 disabled:opacity-40 transition-colors"
                >
                  Próximo →
                </button>
              </div>
            </div>
          )}
        </>
      )}

      <ConfirmDialog
        open={deleteId !== null}
        title="Remover lote"
        description="Esta ação não pode ser desfeita. O lote e seus dados serão removidos permanentemente."
        confirmLabel="Remover"
        onConfirm={() => deleteId && deleteMutation.mutate(deleteId)}
        onCancel={() => setDeleteId(null)}
      />
    </div>
  )
}

// frontendV2/src/app/features/extrato/lotes/lotes.component.ts
import {
  ChangeDetectionStrategy, Component, OnInit,
  inject, signal
} from '@angular/core';
import { RouterLink } from '@angular/router';
import { LoteService } from '../../../core/services/lote.service';
import { SessionService } from '../../../core/services/session.service';
import { ToastService } from '../../../core/services/toast.service';
import { Lote, LoteStatus } from '../../../core/models/lote.model';
import { BadgeComponent } from '../../../shared/components/badge/badge.component';
import { SpinnerComponent } from '../../../shared/components/spinner/spinner.component';
import { ConfirmDialogComponent } from '../../../shared/components/confirm-dialog/confirm-dialog.component';
import { CnpjPipe } from '../../../shared/pipes/cnpj.pipe';

@Component({
  selector: 'app-lotes',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [RouterLink, BadgeComponent, SpinnerComponent, ConfirmDialogComponent, CnpjPipe],
  template: `
    <div>
      <!-- Filters -->
      <div class="flex items-center gap-3 mb-6 flex-wrap">
        <select
          [value]="filterStatus()"
          (change)="onStatusChange($event)"
          class="h-9 px-3 border border-slate-300 bg-white text-sm text-slate-700 focus:outline-none focus:border-slate-900 transition-colors duration-150"
          aria-label="Filtrar por status"
          data-testid="filter-status"
        >
          <option value="">Todos os status</option>
          <option value="pendente">Pendente</option>
          <option value="processando">Processando</option>
          <option value="concluido">Concluído</option>
          <option value="erro">Erro</option>
        </select>

        <button
          (click)="load()"
          class="h-9 px-3 border border-slate-300 bg-white text-sm text-slate-700 hover:bg-slate-50 transition-colors duration-150 flex items-center gap-1.5"
          data-testid="refresh-btn"
        >
          <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">
            <polyline points="23 4 23 10 17 10"/>
            <path d="M20.49 15a9 9 0 1 1-2.12-9.36L23 10"/>
          </svg>
          Atualizar
        </button>
      </div>

      <!-- Table -->
      @if (loading()) {
        <div class="flex items-center justify-center py-16">
          <app-spinner [size]="32" />
        </div>
      } @else if (lotes().length === 0) {
        <div class="text-center py-16 border border-dashed border-slate-200">
          <svg width="40" height="40" viewBox="0 0 24 24" fill="none" stroke="#CBD5E1" stroke-width="1.5" class="mx-auto mb-3" aria-hidden="true">
            <path d="M9 11l3 3L22 4M21 12v7a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h11"/>
          </svg>
          <p class="text-sm text-slate-400 font-medium">Nenhum lote encontrado</p>
          <p class="text-xs text-slate-300 mt-1">Faça um upload para criar o primeiro lote.</p>
        </div>
      } @else {
        <div class="border border-slate-200 overflow-x-auto">
          <table class="w-full text-sm" aria-label="Lista de lotes">
            <thead class="bg-slate-50 border-b border-slate-200">
              <tr>
                <th scope="col" class="text-left px-4 py-3 text-xs font-medium text-slate-500 uppercase tracking-wider">Protocolo</th>
                <th scope="col" class="text-left px-4 py-3 text-xs font-medium text-slate-500 uppercase tracking-wider">CNPJ</th>
                <th scope="col" class="text-left px-4 py-3 text-xs font-medium text-slate-500 uppercase tracking-wider">Status</th>
                <th scope="col" class="text-left px-4 py-3 text-xs font-medium text-slate-500 uppercase tracking-wider">Criado em</th>
                <th scope="col" class="px-4 py-3 text-xs font-medium text-slate-500 uppercase tracking-wider text-right">Ações</th>
              </tr>
            </thead>
            <tbody class="divide-y divide-slate-100">
              @for (lote of lotes(); track lote.id) {
                <tr class="hover:bg-slate-50/60 transition-colors duration-100">
                  <td class="px-4 py-3 font-mono text-slate-900 text-xs">
                    <a [routerLink]="['/extrato/lotes', lote.id]" class="hover:underline" data-testid="lote-link">
                      {{ lote.protocolo }}
                    </a>
                  </td>
                  <td class="px-4 py-3 font-mono text-slate-600 text-xs">{{ lote.cnpj | cnpj }}</td>
                  <td class="px-4 py-3">
                    <app-badge [value]="lote.status" />
                  </td>
                  <td class="px-4 py-3 text-slate-500 text-xs font-mono">
                    {{ formatDate(lote.criado_em) }}
                  </td>
                  <td class="px-4 py-3">
                    <div class="flex items-center justify-end gap-2">
                      @if (lote.status === 'concluido') {
                        <a
                          [href]="loteService.downloadUrl(lote.id)"
                          target="_blank"
                          class="p-1.5 text-slate-500 hover:text-emerald-700 hover:bg-emerald-50 rounded-sm transition-colors duration-150"
                          title="Download TXT"
                          [attr.aria-label]="'Download TXT do lote ' + lote.protocolo"
                          data-testid="download-btn"
                        >
                          <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">
                            <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/>
                            <polyline points="7 10 12 15 17 10"/>
                            <line x1="12" y1="15" x2="12" y2="3"/>
                          </svg>
                        </a>
                      }
                      @if (lote.status === 'erro') {
                        <button
                          (click)="reprocessar(lote)"
                          class="p-1.5 text-slate-500 hover:text-blue-700 hover:bg-blue-50 rounded-sm transition-colors duration-150"
                          title="Reprocessar"
                          [attr.aria-label]="'Reprocessar lote ' + lote.protocolo"
                          data-testid="reprocess-btn"
                        >
                          <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">
                            <polyline points="23 4 23 10 17 10"/>
                            <path d="M20.49 15a9 9 0 1 1-2.12-9.36L23 10"/>
                          </svg>
                        </button>
                      }
                      <button
                        (click)="confirmDelete(lote)"
                        class="p-1.5 text-slate-500 hover:text-red-700 hover:bg-red-50 rounded-sm transition-colors duration-150"
                        title="Deletar"
                        [attr.aria-label]="'Deletar lote ' + lote.protocolo"
                        data-testid="delete-btn"
                      >
                        <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">
                          <polyline points="3 6 5 6 21 6"/>
                          <path d="M19 6l-1 14a2 2 0 0 1-2 2H8a2 2 0 0 1-2-2L5 6"/>
                          <path d="M10 11v6M14 11v6"/>
                          <path d="M9 6V4a1 1 0 0 1 1-1h4a1 1 0 0 1 1 1v2"/>
                        </svg>
                      </button>
                    </div>
                  </td>
                </tr>
              }
            </tbody>
          </table>
        </div>
      }

      <!-- Confirm dialog -->
      <app-confirm-dialog
        [open]="confirmOpen()"
        title="Deletar lote"
        [message]="'Tem certeza que deseja deletar o lote ' + (loteToDelete()?.protocolo ?? '') + '? Esta ação não pode ser desfeita.'"
        confirmLabel="Deletar"
        cancelLabel="Cancelar"
        (confirmed)="doDelete()"
        (cancelled)="confirmOpen.set(false)"
      />
    </div>
  `,
})
export class LotesComponent implements OnInit {
  readonly loteService = inject(LoteService);
  private readonly sessionService = inject(SessionService);
  private readonly toastService = inject(ToastService);

  lotes = signal<Lote[]>([]);
  loading = signal(false);
  filterStatus = signal<string>('');
  confirmOpen = signal(false);
  loteToDelete = signal<Lote | null>(null);

  ngOnInit(): void { this.load(); }

  load(): void {
    const cnpj = this.sessionService.activeSession()?.cnpj;
    const status = this.filterStatus() || undefined;
    this.loading.set(true);
    this.loteService.list({ cnpj, status: status as import('../../../core/models/lote.model').LoteStatus || undefined }).subscribe({
      next: (l) => { this.lotes.set(l); this.loading.set(false); },
      error: () => { this.loading.set(false); },
    });
  }

  onStatusChange(event: Event): void {
    this.filterStatus.set((event.target as HTMLSelectElement).value);
    this.load();
  }

  formatDate(iso: string): string {
    return new Date(iso).toLocaleDateString('pt-BR', { day: '2-digit', month: '2-digit', year: 'numeric', hour: '2-digit', minute: '2-digit' });
  }

  reprocessar(lote: Lote): void {
    this.loteService.reprocessar(lote.id).subscribe({
      next: () => { this.toastService.info(`Lote ${lote.protocolo} enviado para reprocessamento.`); this.load(); },
      error: () => { this.toastService.error('Erro ao reprocessar o lote.'); },
    });
  }

  confirmDelete(lote: Lote): void {
    this.loteToDelete.set(lote);
    this.confirmOpen.set(true);
  }

  doDelete(): void {
    const lote = this.loteToDelete();
    if (!lote) return;
    this.confirmOpen.set(false);
    this.loteService.delete(lote.id).subscribe({
      next: () => { this.toastService.success(`Lote ${lote.protocolo} deletado.`); this.load(); },
      error: () => { this.toastService.error('Erro ao deletar o lote.'); },
    });
  }
}
