// frontendV2/src/app/shared/components/shell/sidebar.component.ts
import { ChangeDetectionStrategy, Component, input, output } from '@angular/core';
import { RouterLink, RouterLinkActive } from '@angular/router';

interface NavItem {
  label: string;
  route: string;
  icon: 'home' | 'file-text';
}

const NAV_ITEMS: NavItem[] = [
  { label: 'Dashboard', route: '/dashboard', icon: 'home' },
  { label: 'Extrato to TXT', route: '/extrato', icon: 'file-text' },
];

@Component({
  selector: 'app-sidebar',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [RouterLink, RouterLinkActive],
  host: {
    class: 'flex flex-col h-full bg-surface border-r border-slate-200 transition-[width] duration-300 overflow-hidden shrink-0',
    '[class.w-64]': '!collapsed()',
    '[class.w-16]': 'collapsed()',
  },
  template: `
    <!-- Logo area -->
    <div class="flex items-center gap-3 px-4 h-16 border-b border-slate-200 shrink-0">
      <div class="w-8 h-8 bg-slate-900 flex items-center justify-center shrink-0">
        <span class="text-white text-xs font-bold font-mono">EC</span>
      </div>
      @if (!collapsed()) {
        <span class="font-bold text-slate-900 text-sm tracking-tight whitespace-nowrap">
          ECS Extrato
        </span>
      }
    </div>

    <!-- Navigation -->
    <nav class="flex-1 py-4 px-2 space-y-1" aria-label="Menu principal">
      @for (item of navItems; track item.route) {
        <a
          [routerLink]="item.route"
          routerLinkActive="bg-slate-900 text-white"
          [routerLinkActiveOptions]="{ exact: false }"
          class="flex items-center gap-3 px-3 py-2.5 rounded-sm text-slate-600 hover:bg-slate-100 hover:text-slate-900 transition-colors duration-150 group"
          [attr.aria-label]="collapsed() ? item.label : null"
          [attr.title]="collapsed() ? item.label : null"
          data-testid="nav-item"
        >
          <span class="shrink-0" aria-hidden="true">
            @switch (item.icon) {
              @case ('home') {
                <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                  <path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"/>
                  <polyline points="9 22 9 12 15 12 15 22"/>
                </svg>
              }
              @case ('file-text') {
                <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                  <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/>
                  <polyline points="14 2 14 8 20 8"/>
                  <line x1="16" y1="13" x2="8" y2="13"/>
                  <line x1="16" y1="17" x2="8" y2="17"/>
                  <polyline points="10 9 9 9 8 9"/>
                </svg>
              }
            }
          </span>
          @if (!collapsed()) {
            <span class="text-sm font-medium whitespace-nowrap">{{ item.label }}</span>
          }
        </a>
      }
    </nav>

    <!-- Collapse toggle -->
    <div class="px-2 pb-4 border-t border-slate-200 pt-3 shrink-0">
      <button
        (click)="toggleCollapse.emit()"
        class="w-full flex items-center justify-center p-2 text-slate-400 hover:text-slate-900 hover:bg-slate-100 rounded-sm transition-colors duration-150"
        [attr.aria-label]="collapsed() ? 'Expandir menu' : 'Recolher menu'"
        data-testid="sidebar-toggle"
      >
        @if (collapsed()) {
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">
            <polyline points="9 18 15 12 9 6"/>
          </svg>
        } @else {
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">
            <polyline points="15 18 9 12 15 6"/>
          </svg>
        }
      </button>
    </div>
  `,
})
export class SidebarComponent {
  collapsed = input<boolean>(false);
  toggleCollapse = output<void>();
  readonly navItems = NAV_ITEMS;
}

// frontendV3/src/shared/components/layout/sidebar.tsx
import { Link, useRouterState } from '@tanstack/react-router'

const NAV = [
  { href: '/dashboard', label: 'Dashboard', icon: 'M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6' },
  { href: '/extrato/upload', label: 'Upload', icon: 'M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-8l-4-4m0 0L8 8m4-4v12' },
  { href: '/extrato/lotes', label: 'Lotes', icon: 'M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2' },
  { href: '/extrato/import-layout', label: 'Import Layout', icon: 'M4 5a1 1 0 011-1h14a1 1 0 011 1v2a1 1 0 01-1 1H5a1 1 0 01-1-1V5zM4 13a1 1 0 011-1h6a1 1 0 011 1v6a1 1 0 01-1 1H5a1 1 0 01-1-1v-6zM16 13a1 1 0 011-1h2a1 1 0 011 1v6a1 1 0 01-1 1h-2a1 1 0 01-1-1v-6z' },
  { href: '/extrato/output-layout', label: 'Output Layout', icon: 'M8 7H5a2 2 0 00-2 2v9a2 2 0 002 2h14a2 2 0 002-2V9a2 2 0 00-2-2h-3m-1 4l-3 3m0 0l-3-3m3 3V4' },
  { href: '/extrato/mapeamento', label: 'Mapeamento', icon: 'M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z' },
]

export function Sidebar() {
  const { location } = useRouterState()
  const path = location.pathname

  return (
    <aside className="w-56 flex-shrink-0 bg-white border-r border-slate-200 flex flex-col min-h-screen">
      {/* Logo */}
      <div className="px-5 py-4 border-b border-slate-200">
        <span className="text-sm font-bold tracking-tight text-slate-900">ECS</span>
        <span className="ml-1 text-xs text-slate-400">Extrato to TXT</span>
      </div>

      <nav className="flex-1 py-4" aria-label="Menu principal">
        <ul className="space-y-0.5 px-2" role="list">
          {NAV.map(item => {
            const active = path === item.href || path.startsWith(item.href + '/')
            return (
              <li key={item.href}>
                <Link
                  to={item.href}
                  className={`flex items-center gap-2.5 px-3 py-2 text-sm font-medium transition-colors ${
                    active
                      ? 'bg-slate-900 text-white'
                      : 'text-slate-600 hover:bg-slate-100 hover:text-slate-900'
                  }`}
                  aria-current={active ? 'page' : undefined}
                >
                  <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.75" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
                    <path d={item.icon} />
                  </svg>
                  {item.label}
                </Link>
              </li>
            )
          })}
        </ul>
      </nav>

      <div className="px-4 py-3 border-t border-slate-200">
        <p className="text-xs text-slate-400">v3.0.0-mock</p>
      </div>
    </aside>
  )
}
