// frontendV3/src/routes/_authenticated/extrato/upload.tsx
import { createFileRoute, useNavigate } from '@tanstack/react-router'
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import { useRef, useState } from 'react'
import { useForm } from 'react-hook-form'
import { zodResolver } from '@hookform/resolvers/zod'
import { z } from 'zod'
import { api } from '@/lib/api-client'
import type { ImportLayout } from '@/features/import-layout/services/schemas'
import type { OutputProfile } from '@/features/output-layout/services/schemas'
import { LayoutWizard } from '@/features/upload/components/layout-wizard'
import { Spinner } from '@/shared/components/spinner/spinner'
import { useSession } from '@/shared/hooks/use-session'
import { toast } from 'sonner'

export const Route = createFileRoute('/_authenticated/extrato/upload')({
  component: UploadPage,
})

const MONTHS = [
  { value: 1, label: 'Janeiro' }, { value: 2, label: 'Fevereiro' }, { value: 3, label: 'Março' },
  { value: 4, label: 'Abril' }, { value: 5, label: 'Maio' }, { value: 6, label: 'Junho' },
  { value: 7, label: 'Julho' }, { value: 8, label: 'Agosto' }, { value: 9, label: 'Setembro' },
  { value: 10, label: 'Outubro' }, { value: 11, label: 'Novembro' }, { value: 12, label: 'Dezembro' },
]

const currentYear = new Date().getFullYear()
const YEARS = Array.from({ length: 5 }, (_, i) => currentYear - i)

const UploadFormSchema = z.object({
  layout_id: z.string().min(1, 'Selecione um layout'),
  perfil_saida_id: z.string().min(1, 'Selecione um perfil de saída'),
  periodo_mes: z.coerce.number().int().min(1).max(12),
  periodo_ano: z.coerce.number().int().min(2000).max(2099),
})
type UploadForm = z.infer<typeof UploadFormSchema>

function UploadPage() {
  const { session } = useSession()
  const navigate = useNavigate()
  const qc = useQueryClient()
  const fileInputRef = useRef<HTMLInputElement>(null)
  const [arquivo, setArquivo] = useState<File | null>(null)
  const [wizardOpen, setWizardOpen] = useState(false)

  const { register, handleSubmit, watch, formState: { errors } } = useForm<UploadForm>({
    resolver: zodResolver(UploadFormSchema),
    defaultValues: {
      layout_id: '',
      perfil_saida_id: '',
      periodo_mes: new Date().getMonth() + 1,
      periodo_ano: currentYear,
    },
  })

  const selectedLayoutId = watch('layout_id')

  const { data: layouts, isLoading: loadingLayouts } = useQuery({
    queryKey: ['import-layouts', session?.cnpj],
    queryFn: () => api.get<{ items: ImportLayout[] }>('/import-layouts', session?.cnpj ? { cnpj: session.cnpj } : undefined),
  })

  const { data: perfis, isLoading: loadingPerfis } = useQuery({
    queryKey: ['output-layouts'],
    queryFn: () => api.get<{ items: OutputProfile[] }>('/output-layouts'),
  })

  const selectedLayout = layouts?.items.find(l => l.id === selectedLayoutId)

  const uploadMutation = useMutation({
    mutationFn: (values: UploadForm) => {
      const body = {
        ...values,
        cnpj: session?.cnpj ?? '',
        nome_arquivo: arquivo?.name,
      }
      return api.post('/lotes', body)
    },
    onSuccess: () => {
      void qc.invalidateQueries({ queryKey: ['lotes'] })
      toast.success('Lote criado com sucesso!')
      void navigate({ to: '/extrato/lotes' })
    },
    onError: () => toast.error('Erro ao criar lote.'),
  })

  function handleFileChange(e: React.ChangeEvent<HTMLInputElement>) {
    const file = e.target.files?.[0] ?? null
    setArquivo(file)
  }

  function onSubmit(values: UploadForm) {
    if (!arquivo) {
      toast.error('Selecione um arquivo Excel para upload.')
      return
    }
    if (!session?.cnpj) {
      toast.error('Selecione um CNPJ ativo no menu superior.')
      return
    }
    uploadMutation.mutate(values)
  }

  return (
    <div className="max-w-2xl">
      <div className="mb-8">
        <p className="text-xs font-medium text-slate-400 uppercase tracking-widest mb-1">Extrato</p>
        <h1 className="text-2xl font-bold text-slate-900">Upload de Extrato</h1>
        <p className="mt-1 text-sm text-slate-500">Envie um arquivo Excel para processamento contábil.</p>
      </div>

      {!session && (
        <div className="mb-6 flex items-start gap-3 px-4 py-3 bg-amber-50 border border-amber-200">
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" className="text-amber-600 shrink-0 mt-0.5" aria-hidden="true">
            <circle cx="12" cy="12" r="10"/><line x1="12" y1="8" x2="12" y2="12"/><line x1="12" y1="16" x2="12.01" y2="16"/>
          </svg>
          <p className="text-sm text-amber-700">Selecione um CNPJ no menu superior antes de enviar.</p>
        </div>
      )}

      <form onSubmit={handleSubmit(onSubmit)} className="space-y-6">
        {/* Arquivo */}
        <div>
          <label className="block text-sm font-medium text-slate-700 mb-2">Arquivo Excel</label>
          <div
            className="border-2 border-dashed border-slate-300 hover:border-slate-400 transition-colors cursor-pointer"
            onClick={() => fileInputRef.current?.click()}
            onKeyDown={(e) => e.key === 'Enter' && fileInputRef.current?.click()}
            role="button"
            tabIndex={0}
            aria-label="Selecionar arquivo Excel"
          >
            <input
              ref={fileInputRef}
              type="file"
              accept=".xlsx,.xls,.csv"
              className="sr-only"
              onChange={handleFileChange}
              aria-hidden="true"
            />
            {arquivo ? (
              <div className="flex items-center gap-3 px-4 py-4">
                <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" className="text-emerald-600 shrink-0" aria-hidden="true">
                  <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/>
                  <polyline points="14,2 14,8 20,8"/>
                </svg>
                <div>
                  <p className="text-sm font-medium text-slate-900">{arquivo.name}</p>
                  <p className="text-xs text-slate-500">{(arquivo.size / 1024).toFixed(1)} KB · Clique para substituir</p>
                </div>
              </div>
            ) : (
              <div className="flex flex-col items-center gap-2 py-8 text-slate-400">
                <svg width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" aria-hidden="true">
                  <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/>
                  <polyline points="17,8 12,3 7,8"/>
                  <line x1="12" y1="3" x2="12" y2="15"/>
                </svg>
                <p className="text-sm">Clique para selecionar ou arraste o arquivo aqui</p>
                <p className="text-xs">.xlsx, .xls, .csv aceitos</p>
              </div>
            )}
          </div>
        </div>

        {/* Layout + Wizard button */}
        <div>
          <div className="flex items-end gap-3">
            <div className="flex-1">
              <label className="block text-sm font-medium text-slate-700 mb-1">Layout de Importação</label>
              {loadingLayouts ? (
                <div className="flex items-center gap-2 py-2 text-slate-400 text-sm"><Spinner /> Carregando...</div>
              ) : (
                <select
                  {...register('layout_id')}
                  className="w-full border border-slate-300 px-3 py-2 text-sm focus:outline-none focus:ring-1 focus:ring-slate-400 bg-white"
                >
                  <option value="">Selecione um layout...</option>
                  {layouts?.items.filter(l => l.ativo).map(l => (
                    <option key={l.id} value={l.id}>{l.nome}</option>
                  ))}
                </select>
              )}
              {errors.layout_id && <p className="text-xs text-red-600 mt-1">{errors.layout_id.message}</p>}
            </div>
            {selectedLayoutId && arquivo && (
              <button
                type="button"
                onClick={() => setWizardOpen(true)}
                className="px-4 py-2 border border-slate-300 text-sm text-slate-700 hover:bg-slate-50 transition-colors whitespace-nowrap"
              >
                Configurar Layout
              </button>
            )}
          </div>
        </div>

        {/* Perfil de saída */}
        <div>
          <label className="block text-sm font-medium text-slate-700 mb-1">Perfil de Saída</label>
          {loadingPerfis ? (
            <div className="flex items-center gap-2 py-2 text-slate-400 text-sm"><Spinner /> Carregando...</div>
          ) : (
            <select
              {...register('perfil_saida_id')}
              className="w-full border border-slate-300 px-3 py-2 text-sm focus:outline-none focus:ring-1 focus:ring-slate-400 bg-white"
            >
              <option value="">Selecione um perfil...</option>
              {perfis?.items.map(p => (
                <option key={p.id} value={p.id}>{p.nome}{p.padrao ? ' (padrão)' : ''}</option>
              ))}
            </select>
          )}
          {errors.perfil_saida_id && <p className="text-xs text-red-600 mt-1">{errors.perfil_saida_id.message}</p>}
        </div>

        {/* Período */}
        <div>
          <label className="block text-sm font-medium text-slate-700 mb-1">Período de Competência</label>
          <div className="grid grid-cols-2 gap-3">
            <div>
              <select
                {...register('periodo_mes')}
                className="w-full border border-slate-300 px-3 py-2 text-sm focus:outline-none focus:ring-1 focus:ring-slate-400 bg-white"
              >
                {MONTHS.map(m => <option key={m.value} value={m.value}>{m.label}</option>)}
              </select>
              {errors.periodo_mes && <p className="text-xs text-red-600 mt-1">{errors.periodo_mes.message}</p>}
            </div>
            <div>
              <select
                {...register('periodo_ano')}
                className="w-full border border-slate-300 px-3 py-2 text-sm focus:outline-none focus:ring-1 focus:ring-slate-400 bg-white"
              >
                {YEARS.map(y => <option key={y} value={y}>{y}</option>)}
              </select>
              {errors.periodo_ano && <p className="text-xs text-red-600 mt-1">{errors.periodo_ano.message}</p>}
            </div>
          </div>
        </div>

        <div className="flex items-center gap-3 pt-2">
          <button
            type="submit"
            disabled={uploadMutation.isPending || !session}
            className="px-6 py-2.5 bg-slate-900 text-white text-sm font-medium hover:bg-slate-800 disabled:opacity-50 transition-colors inline-flex items-center gap-2"
          >
            {uploadMutation.isPending && <Spinner />}
            Criar Lote
          </button>
          <button
            type="button"
            onClick={() => void navigate({ to: '/extrato/lotes' })}
            className="px-4 py-2.5 text-sm text-slate-600 hover:text-slate-900 transition-colors"
          >
            Cancelar
          </button>
        </div>
      </form>

      {wizardOpen && selectedLayout && (
        <LayoutWizard
          layoutId={selectedLayout.id}
          layoutNome={selectedLayout.nome}
          arquivo={arquivo}
          onClose={() => setWizardOpen(false)}
          onConfirm={() => {
            setWizardOpen(false)
            toast.success('Configuração do layout salva.')
          }}
        />
      )}
    </div>
  )
}

// frontendV2/src/app/features/extrato/upload/upload.component.ts
import {
  ChangeDetectionStrategy, Component, OnInit,
  inject, signal
} from '@angular/core';
import { ReactiveFormsModule, FormBuilder, Validators } from '@angular/forms';
import { Router } from '@angular/router';
import { LoteService } from '../../../core/services/lote.service';
import { ImportLayoutService } from '../../../core/services/import-layout.service';
import { OutputProfileService } from '../../../core/services/output-profile.service';
import { SessionService } from '../../../core/services/session.service';
import { ToastService } from '../../../core/services/toast.service';
import { ImportLayout } from '../../../core/models/import-layout.model';
import { OutputProfile } from '../../../core/models/output-profile.model';
import { SpinnerComponent } from '../../../shared/components/spinner/spinner.component';

@Component({
  selector: 'app-upload',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [ReactiveFormsModule, SpinnerComponent],
  template: `
    <div class="max-w-2xl">
      <form [formGroup]="form" (ngSubmit)="onSubmit()">

        <!-- Drop zone -->
        <div
          class="border-2 border-dashed border-slate-300 bg-slate-50 p-10 text-center mb-6 cursor-pointer hover:border-slate-500 hover:bg-white transition-colors duration-200"
          [class.border-slate-900]="selectedFile()"
          [class.bg-white]="selectedFile()"
          (click)="fileInput.click()"
          (dragover)="onDragOver($event)"
          (dragleave)="onDragLeave($event)"
          (drop)="onDrop($event)"
          role="button"
          tabindex="0"
          [attr.aria-label]="'Área de upload. ' + (selectedFile() ? 'Arquivo: ' + selectedFile()!.name : 'Clique ou arraste um arquivo Excel')"
          (keydown.enter)="fileInput.click()"
          (keydown.space)="fileInput.click()"
          data-testid="drop-zone"
        >
          <input
            #fileInput
            type="file"
            accept=".xls,.xlsx"
            class="hidden"
            (change)="onFileChange($event)"
            data-testid="file-input"
          />

          @if (selectedFile()) {
            <div class="flex items-center justify-center gap-3">
              <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="#10B981" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">
                <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/>
                <polyline points="14 2 14 8 20 8"/>
              </svg>
              <div class="text-left">
                <p class="text-sm font-medium text-slate-900">{{ selectedFile()!.name }}</p>
                <p class="text-xs text-slate-500 font-mono mt-0.5">{{ fileSizeLabel() }}</p>
              </div>
              <button
                type="button"
                (click)="clearFile($event)"
                class="ml-2 text-slate-400 hover:text-red-600 transition-colors duration-150"
                aria-label="Remover arquivo"
              >
                <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true">
                  <line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/>
                </svg>
              </button>
            </div>
          } @else {
            <div>
              <svg width="40" height="40" viewBox="0 0 24 24" fill="none" stroke="#94A3B8" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" class="mx-auto mb-3" aria-hidden="true">
                <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/>
                <polyline points="17 8 12 3 7 8"/>
                <line x1="12" y1="3" x2="12" y2="15"/>
              </svg>
              <p class="text-sm font-medium text-slate-700">Clique ou arraste o arquivo aqui</p>
              <p class="text-xs text-slate-400 mt-1">Aceita: .xls, .xlsx</p>
            </div>
          }
        </div>

        <!-- Periodo -->
        <div class="grid grid-cols-2 gap-4 mb-4">
          <div>
            <label for="periodo_mes" class="block text-xs font-medium text-slate-700 uppercase tracking-wider mb-1.5">Mes</label>
            <select id="periodo_mes" formControlName="periodo_mes"
              class="w-full h-10 px-3 border border-slate-300 bg-white text-sm text-slate-900 focus:outline-none focus:border-slate-900 transition-colors duration-150"
              data-testid="select-mes">
              <option value="">Selecione...</option>
              @for (m of meses; track m.v) {
                <option [value]="m.v">{{ m.label }}</option>
              }
            </select>
          </div>
          <div>
            <label for="periodo_ano" class="block text-xs font-medium text-slate-700 uppercase tracking-wider mb-1.5">Ano</label>
            <input id="periodo_ano" type="number" formControlName="periodo_ano" min="2000" max="2100"
              class="w-full h-10 px-3 border border-slate-300 bg-white text-sm text-slate-900 focus:outline-none focus:border-slate-900 transition-colors duration-150"
              data-testid="input-ano" />
          </div>
        </div>

        <!-- Layout de importacao -->
        <!-- Layout de importacao -->
        <div class="mb-4">
          <label for="layout_id" class="block text-xs font-medium text-slate-700 uppercase tracking-wider mb-1.5">
            Layout de Importação
          </label>
          <select
            id="layout_id"
            formControlName="layout_id"
            class="w-full h-10 px-3 border border-slate-300 bg-white text-sm text-slate-900 focus:outline-none focus:border-slate-900 transition-colors duration-150"
            data-testid="select-import-layout"
          >
            <option value="">Selecione um layout...</option>
            @for (layout of importLayouts(); track layout.id) {
              <option [value]="layout.id">{{ layout.nome }}</option>
            }
          </select>
          @if (loadingLayouts()) {
            <p class="text-xs text-slate-400 mt-1">Carregando layouts...</p>
          }
        </div>

        <!-- Layout de saída -->
        <div class="mb-6">
          <label for="perfil_saida_id" class="block text-xs font-medium text-slate-700 uppercase tracking-wider mb-1.5">
            Layout de Saída
          </label>
          <select
            id="perfil_saida_id"
            formControlName="perfil_saida_id"
            class="w-full h-10 px-3 border border-slate-300 bg-white text-sm text-slate-900 focus:outline-none focus:border-slate-900 transition-colors duration-150"
            data-testid="select-output-profile"
          >
            <option value="">Selecione um perfil...</option>
            @for (profile of outputProfiles(); track profile.id) {
              <option [value]="profile.id">{{ profile.nome }} — {{ profile.sistema_destino_nome }}</option>
            }
          </select>
          @if (loadingProfiles()) {
            <p class="text-xs text-slate-400 mt-1">Carregando perfis...</p>
          }
        </div>

        <!-- Submit -->
        <button
          type="submit"
          [disabled]="submitting() || form.invalid || !selectedFile()"
          class="flex items-center justify-center gap-2 w-full sm:w-auto px-6 py-3 bg-slate-900 text-white text-sm font-medium hover:bg-slate-800 disabled:opacity-50 disabled:cursor-not-allowed transition-colors duration-150"
          data-testid="submit-upload"
        >
          @if (submitting()) {
            <app-spinner [size]="16" />
            Enviando...
          } @else {
            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true">
              <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/>
              <polyline points="17 8 12 3 7 8"/>
              <line x1="12" y1="3" x2="12" y2="15"/>
            </svg>
            Processar Extrato
          }
        </button>
      </form>
    </div>
  `,
})
export class UploadComponent implements OnInit {
  private readonly fb = inject(FormBuilder);
  private readonly loteService = inject(LoteService);
  private readonly importLayoutService = inject(ImportLayoutService);
  private readonly outputProfileService = inject(OutputProfileService);
  private readonly sessionService = inject(SessionService);
  private readonly toastService = inject(ToastService);
  private readonly router = inject(Router);

  selectedFile = signal<File | null>(null);
  submitting = signal(false);
  importLayouts = signal<ImportLayout[]>([]);
  outputProfiles = signal<OutputProfile[]>([]);
  loadingLayouts = signal(false);
  loadingProfiles = signal(false);

  readonly meses = [
    { v: 1, label: '01' }, { v: 2, label: '02' }, { v: 3, label: '03' }, { v: 4, label: '04' },
    { v: 5, label: '05' }, { v: 6, label: '06' }, { v: 7, label: '07' }, { v: 8, label: '08' },
    { v: 9, label: '09' }, { v: 10, label: '10' }, { v: 11, label: '11' }, { v: 12, label: '12' },
  ];

  form = this.fb.group({
    periodo_mes: ['', Validators.required],
    periodo_ano: [new Date().getFullYear(), [Validators.required, Validators.min(2000), Validators.max(2100)]],
    layout_id: ['', Validators.required],
    perfil_saida_id: ['', Validators.required],
  });

  fileSizeLabel(): string {
    const f = this.selectedFile();
    if (!f) return '';
    const kb = f.size / 1024;
    return kb > 1024 ? `${(kb / 1024).toFixed(1)} MB` : `${kb.toFixed(0)} KB`;
  }

  ngOnInit(): void {
    const cnpj = this.sessionService.activeSession()?.cnpj;
    this.loadingLayouts.set(true);
    this.importLayoutService.list(cnpj ? { cnpj } : {}).subscribe({
      next: (l) => { this.importLayouts.set(l); this.loadingLayouts.set(false); },
      error: () => { this.loadingLayouts.set(false); },
    });
    this.loadingProfiles.set(true);
    this.outputProfileService.list({ apenas_ativos: true }).subscribe({
      next: (p) => { this.outputProfiles.set(p); this.loadingProfiles.set(false); },
      error: () => { this.loadingProfiles.set(false); },
    });
  }

  onFileChange(event: Event): void {
    const input = event.target as HTMLInputElement;
    if (input.files?.length) {
      this.selectedFile.set(input.files[0]);
    }
  }

  onDragOver(event: DragEvent): void {
    event.preventDefault();
  }

  onDragLeave(_event: DragEvent): void {}

  onDrop(event: DragEvent): void {
    event.preventDefault();
    const file = event.dataTransfer?.files[0];
    if (file) this.selectedFile.set(file);
  }

  clearFile(event: MouseEvent): void {
    event.stopPropagation();
    this.selectedFile.set(null);
  }

  onSubmit(): void {
    const file = this.selectedFile();
    const cnpj = this.sessionService.activeSession()?.cnpj;
    if (!file || this.form.invalid || !cnpj) return;

    this.submitting.set(true);
    const reader = new FileReader();
    reader.onload = () => {
      const dataUrl = reader.result as string;
      const base64 = dataUrl.substring(dataUrl.indexOf(',') + 1);
      const { periodo_mes, periodo_ano, layout_id, perfil_saida_id } = this.form.getRawValue();

      this.loteService.create({
        cnpj,
        periodo_mes: Number(periodo_mes),
        periodo_ano: Number(periodo_ano),
        arquivo_base64: base64,
        nome_arquivo: file.name,
        layout_id: layout_id ?? undefined,
        perfil_saida_id: perfil_saida_id ?? undefined,
      }).subscribe({
        next: (lote) => {
          this.submitting.set(false);
          this.toastService.success('Lote ' + lote.protocolo + ' criado com sucesso.');
          this.router.navigate(['/extrato/lotes', lote.id]);
        },
        error: (err) => {
          this.submitting.set(false);
          this.toastService.error(err?.error?.detail ?? 'Erro ao processar o extrato.');
        },
      });
    };
    reader.readAsDataURL(file);
  }
}
