// frontendV3/src/features/output-layout/components/output-layout-form.tsx
import { useNavigate, Link } from '@tanstack/react-router'
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import { useForm } from 'react-hook-form'
import { zodResolver } from '@hookform/resolvers/zod'
import { useEffect } from 'react'
import { api } from '@/lib/api-client'
import {
  OutputProfileFormSchema,
  type OutputProfileForm,
  type OutputProfile,
  OUTPUT_SISTEMAS,
} from '@/features/output-layout/services/schemas'
import { Spinner } from '@/shared/components/spinner/spinner'
import { toast } from 'sonner'

interface Props { id?: string }

export function OutputLayoutFormPage({ id }: Props) {
  const isEditing = !!id
  const navigate = useNavigate()
  const qc = useQueryClient()

  const { data: existing, isLoading: loadingExisting } = useQuery({
    queryKey: ['output-profile', id],
    queryFn: () => api.get<OutputProfile>(`/output-profiles/${id!}`),
    enabled: isEditing,
  })

  const {
    register,
    handleSubmit,
    reset,
    watch,
    formState: { errors, isSubmitting },
  } = useForm<OutputProfileForm>({
    resolver: zodResolver(OutputProfileFormSchema),
    defaultValues: {
      nome: '',
      sistema_destino: '',
      formato: '',
      ativo: true,
      padrao: false,
      descricao: '',
    },
  })

  useEffect(() => {
    if (existing) {
      reset({
        nome: existing.nome,
        sistema_destino: existing.sistema_destino,
        formato: existing.formato,
        ativo: existing.ativo,
        padrao: existing.padrao,
        descricao: existing.descricao ?? '',
      })
    }
  }, [existing, reset])

  const mutation = useMutation({
    mutationFn: (body: OutputProfileForm) => isEditing
      ? api.put<OutputProfile>(`/output-profiles/${id!}`, body)
      : api.post<OutputProfile>('/output-profiles', body),
    onSuccess: () => {
      void qc.invalidateQueries({ queryKey: ['output-profiles'] })
      toast.success(isEditing ? 'Perfil atualizado.' : 'Perfil criado.')
      void navigate({ to: '/extrato/output-layout' })
    },
    onError: () => toast.error('Erro ao salvar perfil.'),
  })

  if (isEditing && loadingExisting) {
    return <div className="flex items-center gap-2 py-20 text-slate-400"><Spinner /> Carregando...</div>
  }

  const selectedSistema = watch('sistema_destino')
  const sistemaConfig = OUTPUT_SISTEMAS.find(s => s.value === selectedSistema)

  return (
    <div className="max-w-3xl">
      <Link
        to="/extrato/output-layout"
        className="inline-flex items-center gap-1.5 text-sm text-slate-500 hover:text-slate-900 mb-6 transition-colors"
      >
        <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" aria-hidden="true">
          <polyline points="15 18 9 12 15 6" />
        </svg>
        Voltar
      </Link>

      <h2 className="text-xl font-bold text-slate-900 mb-8">
        {isEditing ? 'Editar Perfil de Saída' : 'Novo Perfil de Saída'}
      </h2>

      <form onSubmit={handleSubmit(body => mutation.mutate(body))} className="space-y-6">
        {/* Identificação */}
        <section className="border border-slate-200 p-6">
          <h3 className="text-xs font-semibold text-slate-700 uppercase tracking-wider mb-4">Identificação</h3>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div className="sm:col-span-2">
              <label htmlFor="ol-nome" className="block text-xs font-medium text-slate-700 uppercase tracking-wider mb-1">
                Nome <span aria-hidden="true" className="text-red-500">*</span>
              </label>
              <input
                id="ol-nome"
                {...register('nome')}
                className="w-full h-9 px-3 border border-slate-300 bg-white text-sm focus:outline-none focus:border-slate-900 transition-colors"
              />
              {errors.nome && <p className="mt-1 text-xs text-red-600">{errors.nome.message}</p>}
            </div>

            <div>
              <label htmlFor="ol-sistema" className="block text-xs font-medium text-slate-700 uppercase tracking-wider mb-1">
                Sistema Destino <span aria-hidden="true" className="text-red-500">*</span>
              </label>
              <select
                id="ol-sistema"
                {...register('sistema_destino')}
                className="w-full h-9 px-3 border border-slate-300 bg-white text-sm focus:outline-none focus:border-slate-900 transition-colors"
              >
                <option value="">Selecione...</option>
                {OUTPUT_SISTEMAS.map(s => (
                  <option key={s.value} value={s.value}>{s.nome}</option>
                ))}
              </select>
              {errors.sistema_destino && (
                <p className="mt-1 text-xs text-red-600">{errors.sistema_destino.message}</p>
              )}
              {sistemaConfig && (
                <p className="mt-1 text-xs text-slate-400">{sistemaConfig.descricao}</p>
              )}
            </div>

            <div>
              <label htmlFor="ol-formato" className="block text-xs font-medium text-slate-700 uppercase tracking-wider mb-1">
                Formato <span aria-hidden="true" className="text-red-500">*</span>
              </label>
              <select
                id="ol-formato"
                {...register('formato')}
                disabled={!selectedSistema}
                className="w-full h-9 px-3 border border-slate-300 bg-white text-sm focus:outline-none focus:border-slate-900 transition-colors disabled:bg-slate-50 disabled:text-slate-400"
              >
                <option value="">Selecione...</option>
                {sistemaConfig?.formatos.map(f => (
                  <option key={f.value} value={f.value}>{f.nome} ({f.extensao})</option>
                ))}
              </select>
              {errors.formato && <p className="mt-1 text-xs text-red-600">{errors.formato.message}</p>}
            </div>

            <div className="sm:col-span-2">
              <label htmlFor="ol-desc" className="block text-xs font-medium text-slate-700 uppercase tracking-wider mb-1">
                Descrição
              </label>
              <input
                id="ol-desc"
                {...register('descricao')}
                className="w-full h-9 px-3 border border-slate-300 bg-white text-sm focus:outline-none focus:border-slate-900 transition-colors"
              />
            </div>

            <div className="flex items-center gap-3">
              <input
                id="ol-ativo"
                type="checkbox"
                {...register('ativo')}
                className="h-4 w-4 border-slate-300 text-slate-900 focus:ring-0"
              />
              <label htmlFor="ol-ativo" className="text-sm text-slate-700">Ativo</label>
            </div>

            <div className="flex items-center gap-3">
              <input
                id="ol-padrao"
                type="checkbox"
                {...register('padrao')}
                className="h-4 w-4 border-slate-300 text-slate-900 focus:ring-0"
              />
              <label htmlFor="ol-padrao" className="text-sm text-slate-700">Perfil padrão</label>
            </div>
          </div>
        </section>

        <div className="flex gap-3 pb-8">
          <button
            type="submit"
            disabled={isSubmitting || mutation.isPending}
            className="px-6 py-2 bg-slate-900 text-white text-sm font-medium hover:bg-slate-800 disabled:opacity-50 transition-colors flex items-center gap-2"
          >
            {(isSubmitting || mutation.isPending) && <Spinner size={14} />}
            {isSubmitting || mutation.isPending ? 'Salvando...' : 'Salvar Perfil'}
          </button>
          <Link
            to="/extrato/output-layout"
            className="px-6 py-2 border border-slate-300 bg-white text-sm font-medium text-slate-700 hover:bg-slate-50 transition-colors"
          >
            Cancelar
          </Link>
        </div>
      </form>
    </div>
  )
}

// frontendV2/src/app/features/extrato/output-layout/output-layout-form.component.ts
import {
  ChangeDetectionStrategy, Component, OnInit,
  inject, signal, computed,
} from '@angular/core';
import { Router, ActivatedRoute, RouterLink } from '@angular/router';
import { ReactiveFormsModule, FormBuilder, Validators } from '@angular/forms';
import { OutputProfileService } from '../../../core/services/output-profile.service';
import { ToastService } from '../../../core/services/toast.service';
import { OutputProfile, OutputSistema } from '../../../core/models/output-profile.model';
import { SpinnerComponent } from '../../../shared/components/spinner/spinner.component';

@Component({
  selector: 'app-output-layout-form',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [ReactiveFormsModule, RouterLink, SpinnerComponent],
  template: `
    @if (loadingProfile()) {
      <div class="flex items-center justify-center py-20">
        <app-spinner [size]="32" />
      </div>
    } @else {
      <div class="max-w-3xl">

        <!-- Back -->
        <a
          routerLink="/extrato/output-layout"
          class="inline-flex items-center gap-1.5 text-sm text-slate-500 hover:text-slate-900 mb-6 transition-colors duration-150"
        >
          <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true">
            <polyline points="15 18 9 12 15 6"/>
          </svg>
          Voltar para Layouts de Saída
        </a>

        <h2 class="text-xl font-bold text-slate-900 mb-8">
          {{ editId() ? 'Editar Perfil de Saída' : 'Novo Perfil de Saída' }}
        </h2>

        <form [formGroup]="form" (ngSubmit)="save()" class="space-y-8">

          <!-- Seção 1: Identificação -->
          <section class="border border-slate-200 p-6">
            <h3 class="text-xs font-semibold text-slate-700 uppercase tracking-wider mb-4">Identificação</h3>
            <div class="grid grid-cols-1 gap-4">
              <div>
                <label for="profile-nome" class="block text-xs font-medium text-slate-700 uppercase tracking-wider mb-1">
                  Nome <span aria-hidden="true" class="text-red-500">*</span>
                </label>
                <input
                  id="profile-nome"
                  type="text"
                  formControlName="nome"
                  class="w-full h-9 px-3 border border-slate-300 bg-white text-sm focus:outline-none focus:border-slate-900 transition-colors duration-150"
                  data-testid="input-nome"
                />
              </div>
              <div>
                <label for="profile-descricao" class="block text-xs font-medium text-slate-700 uppercase tracking-wider mb-1">Descrição</label>
                <input
                  id="profile-descricao"
                  type="text"
                  formControlName="descricao"
                  class="w-full h-9 px-3 border border-slate-300 bg-white text-sm focus:outline-none focus:border-slate-900 transition-colors duration-150"
                  data-testid="input-descricao"
                />
              </div>
            </div>
          </section>

          <!-- Seção 2: Destino -->
          <section class="border border-slate-200 p-6">
            <h3 class="text-xs font-semibold text-slate-700 uppercase tracking-wider mb-4">Configuração de Destino</h3>

            @if (loadingSistemas()) {
              <div class="flex items-center gap-2 py-4 text-sm text-slate-500">
                <app-spinner [size]="16" /> Carregando sistemas...
              </div>
            } @else {
              <div class="grid grid-cols-1 sm:grid-cols-2 gap-4 mb-4">
                <div>
                  <label for="profile-sistema" class="block text-xs font-medium text-slate-700 uppercase tracking-wider mb-1">
                    Sistema Destino <span aria-hidden="true" class="text-red-500">*</span>
                  </label>
                  <select
                    id="profile-sistema"
                    formControlName="sistema_destino"
                    class="w-full h-9 px-3 border border-slate-300 bg-white text-sm focus:outline-none focus:border-slate-900 transition-colors duration-150"
                    data-testid="select-sistema"
                  >
                    <option value="">Selecione...</option>
                    @for (s of sistemas(); track s.value) {
                      <option [value]="s.value">{{ s.nome }}</option>
                    }
                  </select>
                </div>
                <div>
                  <label for="profile-formato" class="block text-xs font-medium text-slate-700 uppercase tracking-wider mb-1">
                    Formato <span aria-hidden="true" class="text-red-500">*</span>
                  </label>
                  <select
                    id="profile-formato"
                    formControlName="formato"
                    class="w-full h-9 px-3 border border-slate-300 bg-white text-sm focus:outline-none focus:border-slate-900 transition-colors duration-150"
                    data-testid="select-formato"
                  >
                    <option value="">Selecione...</option>
                    @for (f of formatosDisponiveis(); track f.value) {
                      <option [value]="f.value">{{ f.nome }}</option>
                    }
                  </select>
                </div>
              </div>

              <div class="flex gap-8">
                <label class="inline-flex items-center gap-2 cursor-pointer">
                  <input
                    type="checkbox"
                    formControlName="ativo"
                    class="h-4 w-4 border-slate-300 focus:ring-0"
                    data-testid="check-ativo"
                  />
                  <span class="text-sm text-slate-700">Ativo</span>
                </label>
                <label class="inline-flex items-center gap-2 cursor-pointer">
                  <input
                    type="checkbox"
                    formControlName="padrao"
                    class="h-4 w-4 border-slate-300 focus:ring-0"
                    data-testid="check-padrao"
                  />
                  <span class="text-sm text-slate-700">Perfil padrão</span>
                </label>
              </div>
            }
          </section>

          <!-- Botões -->
          <div class="flex gap-3 pb-8">
            <button
              type="submit"
              [disabled]="saving() || form.invalid"
              class="px-6 py-2 bg-slate-900 text-white text-sm font-medium hover:bg-slate-800 disabled:opacity-50 transition-colors duration-150"
              data-testid="save-btn"
            >
              @if (saving()) { Salvando... } @else { Salvar Perfil }
            </button>
            <a
              routerLink="/extrato/output-layout"
              class="px-6 py-2 border border-slate-300 bg-white text-sm font-medium text-slate-700 hover:bg-slate-50 transition-colors duration-150"
            >
              Cancelar
            </a>
          </div>

        </form>
      </div>
    }
  `,
})
export class OutputLayoutFormComponent implements OnInit {
  private readonly service      = inject(OutputProfileService);
  private readonly toastService = inject(ToastService);
  private readonly router       = inject(Router);
  private readonly route        = inject(ActivatedRoute);
  private readonly fb           = inject(FormBuilder);

  editId         = signal<string | null>(null);
  loadingProfile = signal(false);
  loadingSistemas = signal(false);
  saving         = signal(false);
  sistemas       = signal<OutputSistema[]>([]);

  form = this.fb.group({
    nome:            ['', Validators.required],
    descricao:       [''],
    sistema_destino: ['', Validators.required],
    formato:         ['', Validators.required],
    ativo:           [true],
    padrao:          [false],
  });

  formatosDisponiveis = computed(() => {
    const sistemaValue = this.form.get('sistema_destino')?.value ?? '';
    const found = this.sistemas().find(s => s.value === sistemaValue);
    return found?.formatos ?? [];
  });

  ngOnInit(): void {
    this.loadingSistemas.set(true);
    this.service.sistemas().subscribe({
      next: (s) => { this.sistemas.set(s); this.loadingSistemas.set(false); },
      error: () => { this.loadingSistemas.set(false); },
    });

    const id = this.route.snapshot.paramMap.get('id');
    if (id) {
      this.editId.set(id);
      this.loadingProfile.set(true);
      this.service.get(id).subscribe({
        next: (p: OutputProfile) => {
          this.form.patchValue({
            nome:            p.nome,
            descricao:       p.descricao ?? '',
            sistema_destino: p.sistema_destino,
            formato:         p.formato,
            ativo:           p.ativo,
            padrao:          p.padrao,
          });
          this.loadingProfile.set(false);
        },
        error: () => { this.loadingProfile.set(false); this.toastService.error('Erro ao carregar perfil.'); },
      });
    }
  }

  save(): void {
    if (this.form.invalid) return;
    const v = this.form.getRawValue();
    const body: Record<string, unknown> = {
      nome:            v['nome'],
      descricao:       v['descricao'] || undefined,
      sistema_destino: v['sistema_destino'],
      formato:         v['formato'],
      ativo:           v['ativo'],
      padrao:          v['padrao'],
    };

    this.saving.set(true);
    const id = this.editId();
    const req = id ? this.service.update(id, body) : this.service.create(body);
    req.subscribe({
      next: () => {
        this.saving.set(false);
        this.toastService.success('Perfil salvo com sucesso.');
        this.router.navigate(['/extrato/output-layout']);
      },
      error: () => { this.saving.set(false); this.toastService.error('Erro ao salvar perfil.'); },
    });
  }
}
