// frontendV2/src/app/shared/components/badge/badge.component.ts
import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';
import { LoteStatus } from '../../../core/models/lote.model';
import { StatusLabelPipe } from '../../pipes/status-label.pipe';

type BadgeVariant = LoteStatus | 'default';

const VARIANT_CLASSES: Record<BadgeVariant, string> = {
  CONCLUIDO:   'bg-emerald-50 text-emerald-700 border border-emerald-200',
  PENDENTE:    'bg-amber-50 text-amber-700 border border-amber-200',
  PROCESSANDO: 'bg-blue-50 text-blue-700 border border-blue-200',
  ERRO:        'bg-red-50 text-red-700 border border-red-200',
  default:     'bg-slate-50 text-slate-700 border border-slate-200',
};

@Component({
  selector: 'app-badge',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [StatusLabelPipe],
  template: `
    <span
      [class]="classes()"
      class="inline-flex items-center px-2 py-0.5 text-xs font-medium font-mono rounded-sm"
    >
      {{ value() | statusLabel }}
    </span>
  `,
})
export class BadgeComponent {
  value = input.required<BadgeVariant | string>();

  classes = computed(() => {
    const v = this.value() as BadgeVariant;
    return VARIANT_CLASSES[v] ?? VARIANT_CLASSES['default'];
  });
}

// frontend/src/components/ui/Badge.jsx
import React from 'react';
import { cn, getStatusConfig } from '../../lib/utils';

export const Badge = ({ className, variant = 'default', children, ...props }) => {
  const variants = {
    default: 'bg-slate-100 text-slate-700',
    secondary: 'bg-slate-100 text-slate-900',
    outline: 'border border-slate-200 text-slate-700',
    success: 'bg-emerald-100 text-emerald-700',
    warning: 'bg-amber-100 text-amber-700',
    destructive: 'bg-red-100 text-red-700',
    info: 'bg-blue-100 text-blue-700',
  };

  return (
    <span
      className={cn(
        'inline-flex items-center rounded-md px-2.5 py-0.5 text-xs font-medium',
        'transition-colors duration-150',
        variants[variant],
        className
      )}
      {...props}
    >
      {children}
    </span>
  );
};

export const StatusBadge = ({ status, className, ...props }) => {
  const config = getStatusConfig(status);
  
  return (
    <span
      className={cn(
        'inline-flex items-center rounded-md px-2.5 py-0.5 text-xs font-medium',
        config.className,
        className
      )}
      {...props}
    >
      {config.label}
    </span>
  );
};
