// frontendV2/src/app/shared/components/badge/badge.component.ts
import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';
import { LoteStatus } from '../../../core/models/lote.model';
import { StatusLabelPipe } from '../../pipes/status-label.pipe';

type BadgeVariant = LoteStatus | 'default';

const VARIANT_CLASSES: Record<BadgeVariant, string> = {
  CONCLUIDO:   'bg-emerald-50 text-emerald-700 border border-emerald-200',
  PENDENTE:    'bg-amber-50 text-amber-700 border border-amber-200',
  PROCESSANDO: 'bg-blue-50 text-blue-700 border border-blue-200',
  ERRO:        'bg-red-50 text-red-700 border border-red-200',
  default:     'bg-slate-50 text-slate-700 border border-slate-200',
};

@Component({
  selector: 'app-badge',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [StatusLabelPipe],
  template: `
    <span
      [class]="classes()"
      class="inline-flex items-center px-2 py-0.5 text-xs font-medium font-mono rounded-sm"
    >
      {{ value() | statusLabel }}
    </span>
  `,
})
export class BadgeComponent {
  value = input.required<BadgeVariant | string>();

  classes = computed(() => {
    const v = this.value() as BadgeVariant;
    return VARIANT_CLASSES[v] ?? VARIANT_CLASSES['default'];
  });
}

// frontendV3/src/shared/components/badge/badge.tsx
interface BadgeProps {
  variant?: 'slate' | 'emerald' | 'amber' | 'red' | 'blue' | 'violet'
  children: React.ReactNode
}

const VARIANTS: Record<NonNullable<BadgeProps['variant']>, string> = {
  slate:   'bg-slate-100 text-slate-700 border-slate-200',
  emerald: 'bg-emerald-50 text-emerald-700 border-emerald-200',
  amber:   'bg-amber-50 text-amber-700 border-amber-200',
  red:     'bg-red-50 text-red-700 border-red-200',
  blue:    'bg-blue-50 text-blue-700 border-blue-200',
  violet:  'bg-violet-50 text-violet-700 border-violet-200',
}

export function Badge({ variant = 'slate', children }: BadgeProps) {
  return (
    <span className={`inline-flex items-center px-2 py-0.5 text-xs font-medium border ${VARIANTS[variant]}`}>
      {children}
    </span>
  )
}
