// frontendV2/src/app/features/extrato/output-layout/output-layout.component.ts
import {
  ChangeDetectionStrategy, Component, OnInit,
  inject, signal
} from '@angular/core';
import { Router } from '@angular/router';
import { OutputProfileService } from '../../../core/services/output-profile.service';
import { ToastService } from '../../../core/services/toast.service';
import { OutputProfile } from '../../../core/models/output-profile.model';
import { SpinnerComponent } from '../../../shared/components/spinner/spinner.component';
import { ConfirmDialogComponent } from '../../../shared/components/confirm-dialog/confirm-dialog.component';

@Component({
  selector: 'app-output-layout',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [SpinnerComponent, ConfirmDialogComponent],
  template: `
    <div class="max-w-4xl">
      <div class="flex items-center justify-between mb-6">
        <div>
          <h2 class="text-xl font-bold text-slate-900">Layouts de Saída</h2>
          <p class="text-sm text-slate-500 mt-0.5">Configure os perfis de exportação TXT para cada sistema contábil.</p>
        </div>
        <button
          (click)="novo()"
          class="inline-flex items-center gap-2 px-4 py-2 bg-slate-900 text-white text-sm font-medium hover:bg-slate-800 transition-colors duration-150"
          data-testid="add-profile-btn"
        >
          <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true">
            <line x1="12" y1="5" x2="12" y2="19"/><line x1="5" y1="12" x2="19" y2="12"/>
          </svg>
          Novo Perfil
        </button>
      </div>

      @if (loading()) {
        <div class="flex justify-center py-12"><app-spinner [size]="28" /></div>
      } @else if (profiles().length === 0) {
        <div class="text-center py-12 border border-dashed border-slate-200">
          <p class="text-sm text-slate-400">Nenhum perfil de saída configurado.</p>
        </div>
      } @else {
        <div class="space-y-2">
          @for (p of profiles(); track p.id) {
            <div class="flex items-center justify-between p-4 bg-white border border-slate-200 hover:border-slate-300 transition-colors duration-150">
              <div>
                <p class="text-sm font-medium text-slate-900">{{ p.nome }}</p>
                <p class="text-xs text-slate-500 mt-0.5">
                  {{ p.sistema_destino_nome }} — <span class="font-mono">{{ p.formato_nome }}</span>
                </p>
                @if (p.descricao) {
                  <p class="text-xs text-slate-400 mt-0.5">{{ p.descricao }}</p>
                }
              </div>
              <div class="flex items-center gap-2">
                @if (p.padrao) {
                  <span class="text-xs px-2 py-0.5 border border-blue-200 bg-blue-50 text-blue-700 font-medium">Padrão</span>
                }
                <span
                  [class]="p.ativo ? 'bg-emerald-50 text-emerald-700 border-emerald-200' : 'bg-slate-100 text-slate-500 border-slate-200'"
                  class="text-xs px-2 py-0.5 border font-medium"
                >
                  {{ p.ativo ? 'Ativo' : 'Inativo' }}
                </span>
                <button
                  (click)="editar(p)"
                  class="p-1.5 text-slate-400 hover:text-slate-900 hover:bg-slate-100 rounded-sm transition-colors duration-150"
                  [attr.aria-label]="'Editar perfil ' + p.nome"
                  data-testid="edit-profile-btn"
                >
                  <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">
                    <path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"/>
                    <path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z"/>
                  </svg>
                </button>
                <button
                  (click)="confirmDel(p)"
                  class="p-1.5 text-slate-400 hover:text-red-600 hover:bg-red-50 rounded-sm transition-colors duration-150"
                  [attr.aria-label]="'Deletar perfil ' + p.nome"
                  data-testid="delete-profile-btn"
                >
                  <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">
                    <polyline points="3 6 5 6 21 6"/>
                    <path d="M19 6l-1 14a2 2 0 0 1-2 2H8a2 2 0 0 1-2-2L5 6"/>
                  </svg>
                </button>
              </div>
            </div>
          }
        </div>
      }

      <app-confirm-dialog
        [open]="confirmOpen()"
        title="Deletar perfil"
        message="Tem certeza que deseja deletar este perfil de saída?"
        confirmLabel="Deletar"
        cancelLabel="Cancelar"
        (confirmed)="doDelete()"
        (cancelled)="confirmOpen.set(false)"
      />
    </div>
  `,
})
export class OutputLayoutComponent implements OnInit {
  private readonly service      = inject(OutputProfileService);
  private readonly toastService = inject(ToastService);
  private readonly router       = inject(Router);

  profiles    = signal<OutputProfile[]>([]);
  loading     = signal(false);
  confirmOpen = signal(false);
  toDelete    = signal<OutputProfile | null>(null);

  ngOnInit(): void { this.load(); }

  load(): void {
    this.loading.set(true);
    this.service.list().subscribe({
      next: (p) => { this.profiles.set(p); this.loading.set(false); },
      error: () => { this.loading.set(false); },
    });
  }

  novo():      void { this.router.navigate(['/extrato/output-layout/new']); }
  editar(p: OutputProfile): void { this.router.navigate(['/extrato/output-layout', p.id, 'edit']); }

  confirmDel(p: OutputProfile): void { this.toDelete.set(p); this.confirmOpen.set(true); }

  doDelete(): void {
    const p = this.toDelete();
    if (!p) return;
    this.confirmOpen.set(false);
    this.service.delete(p.id).subscribe({
      next: () => { this.load(); this.toastService.success('Perfil deletado.'); },
      error: () => { this.toastService.error('Erro ao deletar.'); },
    });
  }
}

// frontendV3/src/routes/_authenticated/extrato/output-layout/index.tsx
import { createFileRoute, useNavigate } from '@tanstack/react-router'
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import { useState } from 'react'
import { api } from '@/lib/api-client'
import type { OutputProfile } from '@/features/output-layout/services/schemas'
import { Badge } from '@/shared/components/badge/badge'
import { ConfirmDialog } from '@/shared/components/confirm-dialog/confirm-dialog'
import { Spinner } from '@/shared/components/spinner/spinner'
import { toast } from 'sonner'

export const Route = createFileRoute('/_authenticated/extrato/output-layout/')({
  component: OutputLayoutListPage,
})

function OutputLayoutListPage() {
  const navigate = useNavigate()
  const qc = useQueryClient()
  const [deleteId, setDeleteId] = useState<string | null>(null)
  const [deleteName, setDeleteName] = useState<string>('')

  const { data, isLoading } = useQuery({
    queryKey: ['output-profiles'],
    queryFn: () => api.get<{ items: OutputProfile[] }>('/output-profiles'),
  })

  const deleteMutation = useMutation({
    mutationFn: (id: string) => api.delete(`/output-profiles/${id}`),
    onSuccess: () => {
      void qc.invalidateQueries({ queryKey: ['output-profiles'] })
      toast.success('Perfil removido.')
      setDeleteId(null)
      setDeleteName('')
    },
    onError: () => toast.error('Erro ao remover.'),
  })

  const handleDeleteClick = (profile: OutputProfile) => {
    setDeleteId(profile.id)
    setDeleteName(profile.nome)
  }

  return (
    <div className="max-w-5xl">
      <div className="flex items-center justify-between mb-6">
        <div>
          <h2 className="text-xl font-bold text-slate-900">Perfis de Saída</h2>
          <p className="text-sm text-slate-500 mt-0.5">Configure os formatos de exportação dos lançamentos.</p>
        </div>
        <button
          onClick={() => void navigate({ to: '/extrato/output-layout/new' })}
          className="inline-flex items-center gap-2 px-4 py-2 bg-slate-900 text-white text-sm font-medium hover:bg-slate-800 transition-colors"
        >
          + Novo Perfil
        </button>
      </div>

      {isLoading ? (
        <div className="flex items-center gap-2 py-8 text-slate-400"><Spinner /> Carregando...</div>
      ) : (
        <div className="border border-slate-200 bg-white">
          <table className="w-full text-sm" aria-label="Perfis de saída">
            <thead className="bg-slate-50 border-b border-slate-200">
              <tr>
                <th scope="col" className="px-4 py-3 text-left text-xs font-medium text-slate-500 uppercase tracking-wider">Nome</th>
                <th scope="col" className="px-4 py-3 text-left text-xs font-medium text-slate-500 uppercase tracking-wider">Sistema</th>
                <th scope="col" className="px-4 py-3 text-left text-xs font-medium text-slate-500 uppercase tracking-wider">Formato</th>
                <th scope="col" className="px-4 py-3 text-left text-xs font-medium text-slate-500 uppercase tracking-wider">Status</th>
                <th scope="col" className="px-4 py-3 text-left text-xs font-medium text-slate-500 uppercase tracking-wider">Padrão</th>
                <th scope="col" className="px-4 py-3 text-right text-xs font-medium text-slate-500 uppercase tracking-wider">Ações</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100">
              {data?.items.map(profile => (
                <tr key={profile.id} className="hover:bg-slate-50/60">
                  <td className="px-4 py-3 font-medium text-slate-900">{profile.nome}</td>
                  <td className="px-4 py-3 text-slate-600">{profile.sistema_destino_nome}</td>
                  <td className="px-4 py-3 text-slate-600">{profile.formato_nome}</td>
                  <td className="px-4 py-3">
                    <Badge variant={profile.ativo ? 'emerald' : 'slate'}>{profile.ativo ? 'Ativo' : 'Inativo'}</Badge>
                  </td>
                  <td className="px-4 py-3">
                    {profile.padrao && <Badge variant="blue">Padrão</Badge>}
                  </td>
                  <td className="px-4 py-3 text-right flex justify-end gap-3">
                    <button
                      onClick={() => void navigate({ to: '/extrato/output-layout/$id/edit', params: { id: profile.id } })}
                      className="text-xs text-slate-600 hover:text-slate-900 transition-colors"
                    >
                      Editar
                    </button>
                    <button
                      onClick={() => handleDeleteClick(profile)}
                      className="text-xs text-red-600 hover:text-red-800 transition-colors"
                      aria-label={`Remover ${profile.nome}`}
                    >
                      Remover
                    </button>
                  </td>
                </tr>
              ))}
              {!data?.items.length && (
                <tr>
                  <td colSpan={6} className="px-4 py-8 text-center text-sm text-slate-400">
                    Nenhum perfil de saída cadastrado.
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      )}

      <ConfirmDialog
        open={deleteId !== null}
        title="Remover perfil"
        description="Esta ação não pode ser desfeita."
        confirmLabel="Remover"
        onConfirm={() => deleteId && deleteMutation.mutate(deleteId)}
        onCancel={() => { setDeleteId(null); setDeleteName('') }}
      />
    </div>
  )
}
